use anyhow::{Context, Result};
use std::path::Path;

use crate::config::DevyConfig;
use crate::modules;
use crate::output;

/// Output format for `devy export`.
#[derive(Debug, Clone, Copy, clap::ValueEnum)]
pub enum ExportFormat {
    /// Generate a `shell.nix` for use with `nix-shell`
    Shell,
    /// Generate a `flake.nix` (default)
    Flake,
}

/// Produces a valid Nix double-quoted string literal from a raw value.
fn nix_string_value(s: &str) -> String {
    let escaped = s
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace("${", "\\${");
    format!("\"{}\"", escaped)
}

/// Returns a Nix attribute name, quoting it if it contains characters that are
/// not valid in a bare Nix identifier.
fn nix_attr_name(k: &str) -> String {
    let is_bare = !k.is_empty()
        && k.bytes().enumerate().all(|(i, b)| {
            b.is_ascii_alphabetic() || b == b'_' || (i > 0 && (b.is_ascii_digit() || b == b'-'))
        });
    if is_bare {
        k.to_string()
    } else {
        format!("\"{}\"", k.replace('"', "\\\""))
    }
}

/// Returns `pkgs.<attr>` lines for each dependency, indented by `indent`.
/// Deps whose module returns `None` from `nix_attr` are omitted.
fn collect_pkg_lines(config: &DevyConfig, indent: &str) -> Vec<String> {
    config
        .dependencies
        .iter()
        .flat_map(|raw| match raw {
            crate::config::RawDependency::Simple(name) => vec![name.clone()],
            crate::config::RawDependency::Configured(map) => map.keys().cloned().collect(),
        })
        .filter_map(|name| {
            let canonical = modules::canonical_name(&name);
            let dep = crate::config::Dependency::simple(canonical);
            let attr = modules::get(canonical).nix_attr(&dep)?;
            if attr.is_empty() {
                None
            } else {
                Some(format!("{indent}pkgs.{attr}"))
            }
        })
        .collect()
}

fn generate_shell_nix(config: &DevyConfig) -> String {
    let pkg_lines = collect_pkg_lines(config, "    ");

    let env_lines: Vec<String> = config
        .environment
        .iter()
        .map(|(k, v)| format!("    {} = {};", nix_attr_name(k), nix_string_value(v)))
        .collect();

    let project_name = config.name.as_deref().unwrap_or("project");

    let mut out = "# Generated by `devy export --format=shell`. Edit to taste.\n\
         { pkgs ? import <nixpkgs> {} }:\n\
         \n\
         pkgs.mkShell {\n\
         \n\
         "
    .to_string();

    if !pkg_lines.is_empty() {
        out.push_str("  packages = with pkgs; [\n");
        for line in &pkg_lines {
            out.push_str(line);
            out.push('\n');
        }
        out.push_str("  ];\n\n");
    }

    if !env_lines.is_empty() {
        out.push_str("  # Environment variables\n");
        for line in &env_lines {
            out.push_str("  ");
            out.push_str(line.trim_start());
            out.push('\n');
        }
        out.push('\n');
    }

    out.push_str(&format!(
        "  shellHook = ''\n    echo \"Entered {project_name} dev shell\"\n  '';\n"
    ));

    out.push_str("}}\n");
    out
}

fn generate_flake_nix(config: &DevyConfig) -> String {
    let pkg_lines = collect_pkg_lines(config, "          ");

    let env_lines: Vec<String> = config
        .environment
        .iter()
        .map(|(k, v)| format!("          {} = {};", nix_attr_name(k), nix_string_value(v)))
        .collect();

    let project_name = config.name.as_deref().unwrap_or("project");

    let mut out = format!(
        "# Generated by `devy export --format=flake`. Edit to taste.\n\
         {{\n\
           description = \"{project_name} development environment\";\n\
         \n\
           inputs.nixpkgs.url = \"github:NixOS/nixpkgs/nixpkgs-unstable\";\n\
         \n\
           outputs = {{ self, nixpkgs }}:\n\
             let\n\
               forAllSystems = nixpkgs.lib.genAttrs [\n\
                 \"x86_64-linux\" \"aarch64-linux\" \"x86_64-darwin\" \"aarch64-darwin\"\n\
               ];\n\
             in {{\n\
               devShells = forAllSystems (system:\n\
                 let pkgs = nixpkgs.legacyPackages.${{system}}; in {{\n\
                   default = pkgs.mkShell {{\n",
    );

    if !pkg_lines.is_empty() {
        out.push_str("            packages = [\n");
        for line in &pkg_lines {
            out.push_str(line);
            out.push('\n');
        }
        out.push_str("            ];\n\n");
    }

    if !env_lines.is_empty() {
        out.push_str("            # Environment variables\n");
        for line in &env_lines {
            out.push_str(line.trim_start());
            out.push('\n');
        }
        out.push('\n');
    }

    out.push_str(&format!(
        "            shellHook = ''\n\
               echo \"Entered {project_name} dev shell\"\n            '';\n"
    ));

    out.push_str("          };\n        }});\n    }};\n}}\n");
    out
}

pub(crate) fn export_impl(
    config: &DevyConfig,
    format: ExportFormat,
    out_path: &Path,
) -> Result<()> {
    let (content, filename) = match format {
        ExportFormat::Shell => (generate_shell_nix(config), "shell.nix"),
        ExportFormat::Flake => (generate_flake_nix(config), "flake.nix"),
    };
    let dest = out_path.join(filename);

    if dest.exists() {
        output::warn(&format!("{} already exists — overwriting", dest.display()));
    }

    std::fs::write(&dest, &content)
        .with_context(|| format!("Failed to write {}", dest.display()))?;

    output::success(&format!("Wrote {}", dest.display()));
    Ok(())
}

#[cfg_attr(test, mutants::skip)] // thin I/O wrapper
pub fn run(format: ExportFormat) -> Result<()> {
    let (config, project_root) = DevyConfig::load_with_root()?;
    output::header("devy export");
    export_impl(&config, format, &project_root)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::DevyConfig;

    fn config_from_yaml(yaml: &str) -> DevyConfig {
        serde_yml::from_str(yaml).unwrap()
    }

    #[test]
    fn module_registry_nix_attrs_are_correct() {
        use crate::config::Dependency;
        use crate::modules;
        let dep = |n| Dependency::simple(n);
        assert_eq!(
            modules::get("redis").nix_attr(&dep("redis")).as_deref(),
            Some("redis")
        );
        assert_eq!(
            modules::get("mysql").nix_attr(&dep("mysql")).as_deref(),
            Some("mysql80")
        );
        assert_eq!(
            modules::get("postgresql")
                .nix_attr(&dep("postgresql"))
                .as_deref(),
            Some("postgresql")
        );
        assert_eq!(
            modules::get("node").nix_attr(&dep("node")).as_deref(),
            Some("nodejs")
        );
        assert_eq!(
            modules::get("rust").nix_attr(&dep("rust")).as_deref(),
            Some("rustup")
        );
        assert_eq!(
            modules::get("python").nix_attr(&dep("python")).as_deref(),
            Some("python3")
        );
        assert_eq!(
            modules::get("go").nix_attr(&dep("go")).as_deref(),
            Some("go")
        );
        assert_eq!(
            modules::get("awscli").nix_attr(&dep("awscli")).as_deref(),
            Some("awscli2")
        );
        assert_eq!(
            modules::get("helm").nix_attr(&dep("helm")).as_deref(),
            Some("kubernetes-helm")
        );
    }

    #[test]
    fn collect_pkg_lines_resolves_aliases() {
        // "postgres" is an alias for "postgresql"; the nix attr must be "postgresql".
        let config = config_from_yaml("dependencies:\n  - postgres\n");
        let lines = collect_pkg_lines(&config, "");
        assert!(
            lines.iter().any(|l| l.contains("postgresql")),
            "alias 'postgres' must resolve to pkgs.postgresql"
        );
        assert!(
            !lines.iter().any(|l| l.contains("postgres\"")),
            "must not emit pkgs.postgres"
        );
    }

    #[test]
    fn generate_shell_nix_contains_package_entries() {
        let config = config_from_yaml("dependencies:\n  - redis\n  - node\n");
        let out = generate_shell_nix(&config);
        assert!(out.contains("pkgs.redis"), "expected redis in shell.nix");
        assert!(out.contains("pkgs.nodejs"), "expected nodejs in shell.nix");
        assert!(out.contains("mkShell"), "expected mkShell in shell.nix");
    }

    #[test]
    fn generate_flake_nix_contains_package_entries() {
        let config = config_from_yaml("dependencies:\n  - python\n  - postgresql\n");
        let out = generate_flake_nix(&config);
        assert!(out.contains("pkgs.python3"));
        assert!(out.contains("pkgs.postgresql"));
        assert!(out.contains("devShells"));
        assert!(out.contains("nixpkgs-unstable"));
    }

    #[test]
    fn generate_shell_nix_includes_env_vars() {
        let config = config_from_yaml(
            "dependencies:\n  - redis\nenvironment:\n  DATABASE_URL: \"postgres://localhost/dev\"\n",
        );
        let out = generate_shell_nix(&config);
        assert!(
            out.contains("DATABASE_URL = \"postgres://localhost/dev\";"),
            "env var must be properly quoted in shell.nix, got:\n{out}"
        );
    }

    #[test]
    fn nix_string_value_escapes_special_chars() {
        assert_eq!(nix_string_value(r#"say "hi""#), r#""say \"hi\"""#);
        assert_eq!(nix_string_value(r"back\slash"), r#""back\\slash""#);
        assert_eq!(nix_string_value("${FOO}"), r#""\${FOO}""#);
        assert_eq!(nix_string_value("plain"), "\"plain\"");
    }

    #[test]
    fn nix_attr_name_quotes_unsafe_keys() {
        assert_eq!(nix_attr_name("NORMAL_KEY"), "NORMAL_KEY");
        assert_eq!(nix_attr_name("MY-VAR"), "MY-VAR");
        assert_eq!(nix_attr_name("has space"), "\"has space\"");
        assert_eq!(nix_attr_name(""), "\"\"");
        assert_eq!(nix_attr_name("123starts_digit"), "\"123starts_digit\"");
    }

    #[test]
    fn export_impl_shell_writes_file() {
        let dir = crate::test_support::tmp_dir();
        let config = config_from_yaml("dependencies:\n  - redis\n");
        export_impl(&config, ExportFormat::Shell, &dir).unwrap();
        let written = std::fs::read_to_string(dir.join("shell.nix")).unwrap();
        assert!(written.contains("pkgs.redis"));
    }

    #[test]
    fn export_impl_flake_writes_file() {
        let dir = crate::test_support::tmp_dir();
        let config = config_from_yaml("dependencies:\n  - node\n");
        export_impl(&config, ExportFormat::Flake, &dir).unwrap();
        let written = std::fs::read_to_string(dir.join("flake.nix")).unwrap();
        assert!(written.contains("pkgs.nodejs"));
        assert!(written.contains("devShells"));
    }

    #[test]
    fn generate_flake_nix_includes_env_vars() {
        let config =
            config_from_yaml("dependencies:\n  - node\nenvironment:\n  API_KEY: \"secret\"\n");
        let out = generate_flake_nix(&config);
        assert!(
            out.contains("API_KEY = \"secret\";"),
            "env var must be properly quoted in flake.nix, got:\n{out}"
        );
    }

    #[test]
    fn export_impl_warns_on_overwrite() {
        let dir = crate::test_support::tmp_dir();
        let config = config_from_yaml("dependencies:\n  - redis\n");
        // Write the file once to trigger the overwrite branch.
        export_impl(&config, ExportFormat::Shell, &dir).unwrap();
        let warn_count = crate::output::with_warn_capture(|| {
            export_impl(&config, ExportFormat::Shell, &dir).unwrap();
        });
        assert_eq!(warn_count, 1, "must warn exactly once when overwriting");
    }
}
