use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::path::Path;

pub const PATH: &str = "envy.lock";

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct LockFile {
    pub dependencies: Vec<LockedDep>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct LockedDep {
    pub name: String,
    pub resolved_version: Option<String>,
    pub source: String,
}

impl LockFile {
    pub fn load() -> Result<Option<Self>> {
        let path = Path::new(PATH);
        if !path.exists() {
            return Ok(None);
        }
        let content = std::fs::read_to_string(path).context("Failed to read envy.lock")?;
        let lock = serde_yaml::from_str(&content).context("Failed to parse envy.lock")?;
        Ok(Some(lock))
    }

    pub fn write(&self) -> Result<()> {
        let body = serde_yaml::to_string(self).context("Failed to serialize lock file")?;
        let content = format!("# Generated by envy — do not edit manually\n{body}");
        std::fs::write(PATH, content).context("Failed to write envy.lock")
    }

    pub fn get(&self, name: &str) -> Option<&LockedDep> {
        self.dependencies.iter().find(|d| d.name == name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmp_dir() -> std::path::PathBuf {
        use std::sync::atomic::{AtomicU64, Ordering};
        static N: AtomicU64 = AtomicU64::new(0);
        let dir = std::env::temp_dir().join(format!(
            "envy_lock_{}_{}",
            std::process::id(),
            N.fetch_add(1, Ordering::Relaxed)
        ));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    // ── LockFile::get ─────────────────────────────────────────────────────────

    #[test]
    fn get_returns_dep_when_found() {
        let lock = LockFile {
            dependencies: vec![
                LockedDep {
                    name: "node".into(),
                    resolved_version: Some("20.11.0".into()),
                    source: "homebrew".into(),
                },
                LockedDep {
                    name: "redis".into(),
                    resolved_version: None,
                    source: "homebrew".into(),
                },
            ],
        };
        let dep = lock.get("node").unwrap();
        assert_eq!(dep.name, "node");
        assert_eq!(dep.resolved_version, Some("20.11.0".into()));
    }

    #[test]
    fn get_returns_none_when_not_found() {
        let lock = LockFile {
            dependencies: vec![LockedDep {
                name: "node".into(),
                resolved_version: None,
                source: "homebrew".into(),
            }],
        };
        assert!(lock.get("mysql").is_none());
    }

    #[test]
    fn get_on_empty_lock_returns_none() {
        let lock = LockFile::default();
        assert!(lock.get("anything").is_none());
    }

    // ── LockFile serde round-trip ─────────────────────────────────────────────

    #[test]
    fn serde_roundtrip_preserves_all_fields() {
        let original = LockFile {
            dependencies: vec![
                LockedDep {
                    name: "node".into(),
                    resolved_version: Some("20.0.0".into()),
                    source: "homebrew".into(),
                },
                LockedDep {
                    name: "rust".into(),
                    resolved_version: None,
                    source: "rustup".into(),
                },
            ],
        };
        let yaml = serde_yaml::to_string(&original).unwrap();
        let parsed: LockFile = serde_yaml::from_str(&yaml).unwrap();
        assert_eq!(parsed.dependencies.len(), 2);
        assert_eq!(parsed.dependencies[0].name, "node");
        assert_eq!(
            parsed.dependencies[0].resolved_version,
            Some("20.0.0".into())
        );
        assert_eq!(parsed.dependencies[1].source, "rustup");
        assert!(parsed.dependencies[1].resolved_version.is_none());
    }

    #[test]
    fn deserialize_valid_lock_yaml() {
        let yaml =
            "dependencies:\n- name: node\n  resolved_version: '20.0.0'\n  source: homebrew\n";
        let lock: LockFile = serde_yaml::from_str(yaml).unwrap();
        assert_eq!(lock.dependencies[0].name, "node");
        assert_eq!(lock.dependencies[0].resolved_version, Some("20.0.0".into()));
    }

    // ── LockFile::write ───────────────────────────────────────────────────────

    #[test]
    fn write_content_includes_header_and_dep_name() {
        // Verify write() produces the expected format by serializing to a temp file
        // using an absolute path via std::env::set_current_dir protected by a mutex.
        use std::sync::Mutex;
        static LOCK: Mutex<()> = Mutex::new(());
        let _guard = LOCK.lock().unwrap();

        let dir = tmp_dir();
        let original = std::env::current_dir().unwrap();
        std::env::set_current_dir(&dir).unwrap();

        let lock = LockFile {
            dependencies: vec![LockedDep {
                name: "redis".into(),
                resolved_version: Some("7.2.3".into()),
                source: "homebrew".into(),
            }],
        };
        lock.write().unwrap();
        let content = std::fs::read_to_string(PATH).unwrap();

        std::env::set_current_dir(&original).unwrap();
        let _ = std::fs::remove_dir_all(&dir);

        assert!(content.starts_with("# Generated by envy"));
        assert!(content.contains("redis"));
    }
}
