use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::Path;

pub const PATH: &str = "envy.lock";

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct LockFile {
    pub dependencies: HashMap<String, LockedDep>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct LockedDep {
    pub resolved_version: Option<String>,
    pub source: String,
}

impl LockFile {
    pub fn load(path: &Path) -> Result<Option<Self>> {
        if !path.exists() {
            return Ok(None);
        }
        let content =
            std::fs::read_to_string(path).context("Failed to read envy.lock")?;
        let lock = serde_yaml::from_str(&content).context("Failed to parse envy.lock")?;
        Ok(Some(lock))
    }

    pub fn write(&self, path: &Path) -> Result<()> {
        let body = serde_yaml::to_string(self).context("Failed to serialize lock file")?;
        let content = format!("# Generated by envy — do not edit manually\n{body}");
        std::fs::write(path, content).context("Failed to write envy.lock")
    }

    pub fn get(&self, name: &str) -> Option<&LockedDep> {
        self.dependencies.get(name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmp_dir() -> std::path::PathBuf {
        use std::sync::atomic::{AtomicU64, Ordering};
        static N: AtomicU64 = AtomicU64::new(0);
        let dir = std::env::temp_dir().join(format!(
            "envy_lock_{}_{}",
            std::process::id(),
            N.fetch_add(1, Ordering::Relaxed)
        ));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn lock_path(dir: &std::path::Path) -> std::path::PathBuf {
        dir.join(PATH)
    }

    // ── LockFile::get ─────────────────────────────────────────────────────────

    #[test]
    fn get_returns_dep_when_found() {
        let mut deps = HashMap::new();
        deps.insert(
            "node".into(),
            LockedDep {
                resolved_version: Some("20.11.0".into()),
                source: "homebrew".into(),
            },
        );
        deps.insert(
            "redis".into(),
            LockedDep {
                resolved_version: None,
                source: "homebrew".into(),
            },
        );
        let lock = LockFile { dependencies: deps };
        let dep = lock.get("node").unwrap();
        assert_eq!(dep.resolved_version, Some("20.11.0".into()));
    }

    #[test]
    fn get_returns_none_when_not_found() {
        let mut deps = HashMap::new();
        deps.insert(
            "node".into(),
            LockedDep {
                resolved_version: None,
                source: "homebrew".into(),
            },
        );
        let lock = LockFile { dependencies: deps };
        assert!(lock.get("mysql").is_none());
    }

    #[test]
    fn get_on_empty_lock_returns_none() {
        let lock = LockFile::default();
        assert!(lock.get("anything").is_none());
    }

    // ── LockFile serde round-trip ─────────────────────────────────────────────

    #[test]
    fn serde_roundtrip_preserves_all_fields() {
        let mut deps = HashMap::new();
        deps.insert(
            "node".into(),
            LockedDep {
                resolved_version: Some("20.0.0".into()),
                source: "homebrew".into(),
            },
        );
        deps.insert(
            "rust".into(),
            LockedDep {
                resolved_version: None,
                source: "rustup".into(),
            },
        );
        let original = LockFile { dependencies: deps };
        let yaml = serde_yaml::to_string(&original).unwrap();
        let parsed: LockFile = serde_yaml::from_str(&yaml).unwrap();
        assert_eq!(parsed.dependencies.len(), 2);
        assert_eq!(
            parsed.get("node").unwrap().resolved_version,
            Some("20.0.0".into())
        );
        assert_eq!(parsed.get("rust").unwrap().source, "rustup");
        assert!(parsed.get("rust").unwrap().resolved_version.is_none());
    }

    #[test]
    fn deserialize_valid_lock_yaml() {
        let yaml = "dependencies:\n  node:\n    resolved_version: '20.0.0'\n    source: homebrew\n";
        let lock: LockFile = serde_yaml::from_str(yaml).unwrap();
        assert_eq!(
            lock.get("node").unwrap().resolved_version,
            Some("20.0.0".into())
        );
    }

    // ── LockFile::write ───────────────────────────────────────────────────────

    #[test]
    fn write_content_includes_header_and_dep_name() {
        let dir = tmp_dir();
        let path = lock_path(&dir);

        let mut deps = HashMap::new();
        deps.insert(
            "redis".into(),
            LockedDep {
                resolved_version: Some("7.2.3".into()),
                source: "homebrew".into(),
            },
        );
        let lock = LockFile { dependencies: deps };
        lock.write(&path).unwrap();
        let content = std::fs::read_to_string(&path).unwrap();

        let _ = std::fs::remove_dir_all(&dir);

        assert!(content.starts_with("# Generated by envy"));
        assert!(content.contains("redis"));
    }

    #[test]
    fn load_returns_none_when_file_absent() {
        let dir = tmp_dir();
        let path = lock_path(&dir);
        assert!(LockFile::load(&path).unwrap().is_none());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn load_round_trips_written_file() {
        let dir = tmp_dir();
        let path = lock_path(&dir);

        let mut deps = HashMap::new();
        deps.insert(
            "pg".into(),
            LockedDep {
                resolved_version: Some("16.0".into()),
                source: "homebrew".into(),
            },
        );
        let lock = LockFile { dependencies: deps };
        lock.write(&path).unwrap();

        let loaded = LockFile::load(&path).unwrap().unwrap();
        assert_eq!(
            loaded.get("pg").unwrap().resolved_version,
            Some("16.0".into())
        );

        let _ = std::fs::remove_dir_all(&dir);
    }
}
