use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::Path;

pub const PATH: &str = "devy.lock";

fn default_lock_version() -> u32 {
    1
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LockFile {
    #[serde(default = "default_lock_version")]
    pub version: u32,
    pub dependencies: BTreeMap<String, LockedDep>,
}

impl Default for LockFile {
    fn default() -> Self {
        Self {
            version: default_lock_version(),
            dependencies: BTreeMap::new(),
        }
    }
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct LockedDep {
    pub resolved_version: Option<String>,
    /// Install source (e.g. "homebrew", "apt", "rustup", "rbenv").
    /// Recorded for future tooling (e.g. `devy remove`, migration guides).
    /// Not read back by any current command.
    pub source: String,
}

impl LockFile {
    pub fn load(path: &Path) -> Result<Option<Self>> {
        let content = match std::fs::read_to_string(path) {
            Ok(s) => s,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(None),
            Err(e) => return Err(e).context("Failed to read devy.lock"),
        };
        let lock: Self = serde_yml::from_str(&content).context("Failed to parse devy.lock")?;
        if lock.version > 1 {
            anyhow::bail!(
                "devy.lock was written by a newer version of devy (format version {}). \
                 Update devy to read this file.",
                lock.version
            );
        }
        Ok(Some(lock))
    }

    pub fn write(&self, path: &Path) -> Result<()> {
        let body = serde_yml::to_string(self).context("Failed to serialize lock file")?;
        let content = format!("# Generated by devy — do not edit manually\n{body}");
        let tmp = path.with_file_name({
            let mut name = path
                .file_name()
                .map(std::ffi::OsStr::to_os_string)
                .unwrap_or_else(|| std::ffi::OsString::from("devy.lock"));
            name.push(format!(".{}.tmp", std::process::id()));
            name
        });
        std::fs::write(&tmp, content).context("Failed to write devy.lock (tmp)")?;
        std::fs::rename(&tmp, path).context("Failed to finalize devy.lock")?;
        Ok(())
    }

    pub fn get(&self, name: &str) -> Option<&LockedDep> {
        self.dependencies.get(name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmp_dir() -> crate::test_support::TempDir {
        crate::test_support::tmp_dir()
    }

    fn lock_path(dir: &std::path::Path) -> std::path::PathBuf {
        dir.join(PATH)
    }

    // ── LockFile::get ─────────────────────────────────────────────────────────

    #[test]
    fn get_returns_dep_when_found() {
        let mut deps = BTreeMap::new();
        deps.insert(
            "node".into(),
            LockedDep {
                resolved_version: Some("20.11.0".into()),
                source: "homebrew".into(),
            },
        );
        deps.insert(
            "redis".into(),
            LockedDep {
                resolved_version: None,
                source: "homebrew".into(),
            },
        );
        let lock = LockFile {
            dependencies: deps,
            ..Default::default()
        };
        let dep = lock.get("node").unwrap();
        assert_eq!(dep.resolved_version, Some("20.11.0".into()));
    }

    #[test]
    fn get_returns_none_when_not_found() {
        let mut deps = BTreeMap::new();
        deps.insert(
            "node".into(),
            LockedDep {
                resolved_version: None,
                source: "homebrew".into(),
            },
        );
        let lock = LockFile {
            dependencies: deps,
            ..Default::default()
        };
        assert!(lock.get("mysql").is_none());
    }

    #[test]
    fn get_on_empty_lock_returns_none() {
        let lock = LockFile::default();
        assert!(lock.get("anything").is_none());
    }

    // ── LockFile serde round-trip ─────────────────────────────────────────────

    #[test]
    fn serde_roundtrip_preserves_all_fields() {
        let mut deps = BTreeMap::new();
        deps.insert(
            "node".into(),
            LockedDep {
                resolved_version: Some("20.0.0".into()),
                source: "homebrew".into(),
            },
        );
        deps.insert(
            "rust".into(),
            LockedDep {
                resolved_version: None,
                source: "rustup".into(),
            },
        );
        let original = LockFile {
            dependencies: deps,
            ..Default::default()
        };
        let yaml = serde_yml::to_string(&original).unwrap();
        let parsed: LockFile = serde_yml::from_str(&yaml).unwrap();
        assert_eq!(parsed.dependencies.len(), 2);
        assert_eq!(
            parsed.get("node").unwrap().resolved_version,
            Some("20.0.0".into())
        );
        assert_eq!(parsed.get("rust").unwrap().source, "rustup");
        assert!(parsed.get("rust").unwrap().resolved_version.is_none());
    }

    #[test]
    fn deserialize_valid_lock_yaml() {
        let yaml = "dependencies:\n  node:\n    resolved_version: '20.0.0'\n    source: homebrew\n";
        let lock: LockFile = serde_yml::from_str(yaml).unwrap();
        assert_eq!(
            lock.get("node").unwrap().resolved_version,
            Some("20.0.0".into())
        );
    }

    // ── LockFile::write ───────────────────────────────────────────────────────

    #[test]
    fn write_content_includes_header_and_dep_name() {
        let dir = tmp_dir();
        let path = lock_path(&dir);

        let mut deps = BTreeMap::new();
        deps.insert(
            "redis".into(),
            LockedDep {
                resolved_version: Some("7.2.3".into()),
                source: "homebrew".into(),
            },
        );
        let lock = LockFile {
            dependencies: deps,
            ..Default::default()
        };
        lock.write(&path).unwrap();
        let content = std::fs::read_to_string(&path).unwrap();

        assert!(content.starts_with("# Generated by devy"));
        assert!(content.contains("redis"));
    }

    #[test]
    fn load_returns_none_when_file_absent() {
        let dir = tmp_dir();
        let path = lock_path(&dir);
        assert!(LockFile::load(&path).unwrap().is_none());
    }

    #[test]
    fn write_does_not_leave_tmp_file() {
        let dir = tmp_dir();
        let path = lock_path(&dir);
        let lock = LockFile::default();
        lock.write(&path).unwrap();
        assert!(path.exists(), "lock file must exist after write");
        assert!(
            !path.with_extension("lock.tmp").exists(),
            "temp file must not remain after a successful write"
        );
    }

    #[test]
    fn write_does_not_leave_pid_tmp_file() {
        let dir = tmp_dir();
        let path = lock_path(&dir);
        let lock = LockFile::default();
        lock.write(&path).unwrap();
        assert!(path.exists(), "lock file must exist after write");
        let pid_tmp = path.with_file_name(format!("devy.lock.{}.tmp", std::process::id()));
        assert!(
            !pid_tmp.exists(),
            "PID-namespaced temp file must not remain after a successful write"
        );
    }

    #[test]
    fn load_rejects_future_version() {
        let dir = tmp_dir();
        let path = lock_path(&dir);
        std::fs::write(
            &path,
            "version: 99\ndependencies:\n  node:\n    resolved_version: '20.0.0'\n    source: homebrew\n",
        )
        .unwrap();
        let result = LockFile::load(&path);
        assert!(
            result.is_err(),
            "load must reject lock files from future versions"
        );
        assert!(
            result.unwrap_err().to_string().contains("99"),
            "error must mention the unsupported version number"
        );
    }

    #[test]
    fn load_accepts_missing_version_as_v1() {
        let dir = tmp_dir();
        let path = lock_path(&dir);
        std::fs::write(
            &path,
            "dependencies:\n  node:\n    resolved_version: '20.0.0'\n    source: homebrew\n",
        )
        .unwrap();
        let lock = LockFile::load(&path).unwrap().unwrap();
        assert_eq!(
            lock.version, 1,
            "lock without version field must default to 1"
        );
        assert!(lock.get("node").is_some());
    }

    #[test]
    fn load_round_trips_written_file() {
        let dir = tmp_dir();
        let path = lock_path(&dir);

        let mut deps = BTreeMap::new();
        deps.insert(
            "pg".into(),
            LockedDep {
                resolved_version: Some("16.0".into()),
                source: "homebrew".into(),
            },
        );
        let lock = LockFile {
            dependencies: deps,
            ..Default::default()
        };
        lock.write(&path).unwrap();

        let loaded = LockFile::load(&path).unwrap().unwrap();
        assert_eq!(
            loaded.get("pg").unwrap().resolved_version,
            Some("16.0".into())
        );
    }
}
